#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
# Configure Nginx to listen on port 80
sed -i 's/.*listen 80.*/    listen 80;/g' /etc/nginx/sites-available/default
service nginx start
