#!/usr/bin/env bash
# To configure nginx listening on port 80

#remove the default Nginx
rm /etc/nginx/sites-enabled/default
#configure Nginx to listen on port 80 of all the server’s active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
