#!/usr/bin/env bash
#configure Nginx to listen on port 80 of all the server’s active IPv4 IPs

# To create a symbolic link (-s option) between the Nginx 
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# To restart nginx
service nginx restart
# To Terminate
kill "$(pgrep 'nginx' | head -1)"
