#!/usr/bin/env bash
# Displays "Best school" on the 9th iteration it displays "Hi"

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best school"
	(( count++ ))
done
