#!/usr/bin/env bash
# Code to get Apache and when apache2 is running on the container it will return a page containing "Hello Holberton"
echo "ServerName localhost" >> /etc/apache2.conf
service apache2 start
